names = [
    {'name': 'Andreas Thompson', 'mail': 'andreas.thompson@visma.com'},
    {'name': 'Jan Zimmer', 'mail': 'jan.zimmer@visma.com'},
    {'name': 'Carina Rutledal', 'mail': 'carina.rutledal@visma.com'},
    {'name': 'Marton Skjæveland', 'mail': 'marton.skjaveland@visma.com'},
    {'name': 'Thomas Parmer', 'mail': 'thomas.parmer@visma.com'},
    {'name': 'Aleksander Gjersvoll', 'mail': 'aleksander.gjersvoll@visma.com'},
    {'name': 'Andreas Rimolsrønning', 'mail': 'andreas.rimolsronnin@visma.com'},
    {'name': 'Harald Wilhelmsen', 'mail': 'harald.wilhelmsen@visma.com'},
    {'name': 'Hedda Ulve', 'mail': 'hedda.ulve@visma.com'},
    {'name': 'Henrik Kiær', 'mail': 'henrik.kiar@visma.com'},
    {'name': 'Ingvild Høgstøyl', 'mail': 'ingvild.hogstoyl@visma.com'},
    {'name': 'Jonas Espedal', 'mail': 'jonas.espedal@visma.com'},
    {'name': 'Kari Helena Kvandal', 'mail': 'kari.helena.kvandal@visma.com'},
    {'name': 'Kristoffer Fagerheim', 'mail': 'kristoffer.fagerheim@visma.com'},
    {'name': 'Ole Martin Borge', 'mail': 'ole.borge@visma.com'},
    {'name': 'Sondre Omland', 'mail': 'sondre.omland@visma.com'},
    {'name': 'Stig Martin Liavåg', 'mail': 'stig-martin.liavag@visma.com'},
    {'name': 'Mikal Stapnes', 'mail': 'mikal.stapnes@visma.com'}
    ]
