names = ['Andreas Thompson',
         'Espen Sørhaug',
         'Jan Zimmer',
         'Mikal Stapnes',
         'Carina Rutledal',
         'Marton Skjæveland',
         'Thomas Parmer',
         'Aleksander Gjersvoll',
         'Andreas Rimolsrønning',
         'Harald Wilhelmsen',
         'Hedda Ulve',
         'Henrik Kiær',
         'Kristoffer Fagerheim',
         'Ole Martin Borge',
         'Stig-Martin Liavåg',
         'Tomas Spangelo']
